"""add receipt_code to orders

Revision ID: e32efcb9f70a
Revises: e4c3f4bd9d89
Create Date: 2026-05-12 02:04:36.396907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32efcb9f70a'
down_revision = 'e4c3f4bd9d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_receipt_code'), ['receipt_code'], unique=True)

    # ### end Alembic commands ###
    
    # Generar receipt_code para órdenes existentes
    connection = op.get_bind()
    orders = connection.execute(sa.text("SELECT id, created_at FROM orders ORDER BY id")).fetchall()
    
    for order_id, created_at in orders:
        if created_at:
            date_str = created_at.strftime('%Y%m%d') if hasattr(created_at, 'strftime') else created_at[:10].replace('-', '')
        else:
            date_str = '20260101'
        
        receipt_code = f"MIZ-{date_str}-{order_id:05d}"
        connection.execute(
            sa.text("UPDATE orders SET receipt_code = :code WHERE id = :id"),
            {"code": receipt_code, "id": order_id}
        )
    
    connection.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_receipt_code'))
        batch_op.drop_column('receipt_code')

    # ### end Alembic commands ###
